site_name: Credit Card Fraud Detection Handbook
site_url: https://anguyenthecrazier.github.io/251120-Credit-Card-Fraud-Detection-Handbook/
site_description: A complete end-to-end analysis for building a hybrid machine-learning credit card fraud detection system by Group 6 - Queen Mary University of London MSc Risk Analytics - November 2025

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocs-jupyter
  - awesome-pages

nav:
  - Home: index.md
  - Interactive Demo: demo.md

  - Exploratory Data Analysis:
      - EDA: notebooks/EDA_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb

  - Models:
      - Overview (Full Notebook): notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb
      - Unsupervised:
          - Isolation Forest: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#isolation-forest
          - Local Outlier Factor (LOF): notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#local-outlier-factor-lof
          - One-Class SVM: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#one-class-svm
          - Autoencoder: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#autoencoder
      - Supervised:
          - Logistic Regression: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#logistic-regression
          - Random Forest: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#random-forest
          - XGBoost: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#xgboost
          - LightGBM: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#lightgbm
      - Hybrid:
          - Hybrid Model: notebooks/Models_Risk_Analytics_PLA_Credit_Card_Fraud.ipynb#hybrid-model
  - Conclusion: conclusion.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
